// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RandevuSistemi.Data;

#nullable disable

namespace RandevuSistemi.Migrations
{
    [DbContext(typeof(RandevuDBContext))]
    [Migration("20241121102436_logyapilanmasi")]
    partial class logyapilanmasi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RandevuSistemi.Models.AlinanRandevu", b =>
                {
                    b.Property<int>("AlinanRandevuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlinanRandevuID"));

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("RandevuAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RandevuID")
                        .HasColumnType("int");

                    b.Property<bool>("RandevuIptal")
                        .HasColumnType("bit");

                    b.Property<bool>("RandevuOnay")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("RandevuSaati")
                        .HasColumnType("time");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("AlinanRandevuID");

                    b.HasIndex("RandevuID");

                    b.ToTable("AlinanRandevular");
                });

            modelBuilder.Entity("RandevuSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("KullaniciAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KullaniciOnay")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciTuru")
                        .HasColumnType("int");

                    b.HasKey("KullaniciID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("RandevuSistemi.Models.Randevu", b =>
                {
                    b.Property<int>("RandevuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuID"));

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByKullanici")
                        .HasColumnType("int");

                    b.Property<bool>("RandevuOnay")
                        .HasColumnType("bit");

                    b.Property<int>("RandevuSuresi")
                        .HasColumnType("int");

                    b.Property<int>("RandevuTur")
                        .HasColumnType("int");

                    b.HasKey("RandevuID");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("RandevuSistemi.Models.RandevuTur", b =>
                {
                    b.Property<int>("RandevuTurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuTurID"));

                    b.Property<string>("RandevuTurAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RandevuTurID");

                    b.ToTable("RandevuTurleri");
                });

            modelBuilder.Entity("RandevuSistemi.Models.AlinanRandevu", b =>
                {
                    b.HasOne("RandevuSistemi.Models.Randevu", null)
                        .WithMany("Randevular")
                        .HasForeignKey("RandevuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RandevuSistemi.Models.Randevu", b =>
                {
                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
